### ISSUE TITLE
Cannot run on different computer(linux)

### ISSUE THREAD

**Issue by nian03240324** [22vv0/asphyxia_plugins#12]
Hi,
I use your plugin for a long time, and it always work perfectly.
Because I run KFC on different computers, I try to run asphyxia on my NAS.
However I got error (ただいま回線が混雑しています。再度お試しください。) when I read the card.
I try your DDR plugin on NAS ,and it work perfectly.
My OS is ubuntu 24.04.1 ,plugin 6.0.4 ,asphyxia v1.50c ,kfc-2024110500

**Comment by 22vv0** [comment]
Does asphyxia output any logs? (in dev mode and non-dev node)
Can you provide it here?

**Comment by nian03240324** [comment]
I try to run asphyxia in dev mode, and both DDR and SDVX plugin can not run in this mode.
Here is the log

  [sdvx@asphyxia] error: Failed to load
  [core] error: ⨯ Unable to compile TypeScript:
plugins/sdvx@asphyxia/index.ts:108:32 - error TS2583: Cannot find name 'BigInt'. Do you need to change your target library? Try changing the lib compiler option to 'es2020' or later.

108     gamesession: K.ITEM('s64', BigInt(1)),
                                   ~~~~

TSError: ⨯ Unable to compile TypeScript:
plugins/sdvx@asphyxia/index.ts:108:32 - error TS2583: Cannot find name 'BigInt'. Do you need to change your target library? Try changing the lib compiler option to 'es2020' or later.

108     gamesession: K.ITEM('s64', BigInt(1)),
                                   ~~~~

    at createTSError (/snapshot/build-env/node_modules/ts-node/src/index.ts:513:12)
    at reportTSError (/snapshot/build-env/node_modules/ts-node/src/index.ts:517:19)
    at getOutput (/snapshot/build-env/node_modules/ts-node/src/index.ts:752:36)
    at Object.compile (/snapshot/build-env/node_modules/ts-node/src/index.ts:968:32)
    at Module._compile (/snapshot/build-env/node_modules/ts-node/src/index.ts:1056:42)
    at Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Object..ts (/snapshot/build-env/node_modules/ts-node/src/index.ts:1059:12)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)

  [ddr@asphyxia] error: Failed to load
  [core] error: ⨯ Unable to compile TypeScript:
plugins/ddr@asphyxia/handlers/common.ts:3:32 - error TS2583: Cannot find name 'BigInt'. Do you need to change your target library? Try changing the lib compiler option to 'es2020' or later.

3     gamesession: K.ITEM("s64", BigInt(1)),
                                 ~~~~

TSError: ⨯ Unable to compile TypeScript:
plugins/ddr@asphyxia/handlers/common.ts:3:32 - error TS2583: Cannot find name 'BigInt'. Do you need to change your target library? Try changing the lib compiler option to 'es2020' or later.

3     gamesession: K.ITEM("s64", BigInt(1)),
                                 ~~~~

    at createTSError (/snapshot/build-env/node_modules/ts-node/src/index.ts:513:12)
    at reportTSError (/snapshot/build-env/node_modules/ts-node/src/index.ts:517:19)
    at getOutput (/snapshot/build-env/node_modules/ts-node/src/index.ts:752:36)
    at Object.compile (/snapshot/build-env/node_modules/ts-node/src/index.ts:968:32)
    at Module._compile (/snapshot/build-env/node_modules/ts-node/src/index.ts:1056:42)
    at Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Object..ts (/snapshot/build-env/node_modules/ts-node/src/index.ts:1059:12)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)

**Comment by nian03240324** [comment]
I try to run with another windows PC, and it work.
I think maybe it only happened on linux version.

**Comment by nian03240324** [comment]
I try to edit tsconfig to fix it.
This is logs

  [sdvx@asphyxia] Calling common function
  [sdvx@asphyxia] Game: Exceed Gear
  [sdvx@asphyxia] Unlocking songs
  [sdvx@asphyxia] Sending server information
  [sdvx@asphyxia] TypeError: Cannot read properties of undefined (reading 'arena_items')
  [sdvx@asphyxia] ====================================
  [sdvx@asphyxia] Calling common function
  [sdvx@asphyxia] Game: Exceed Gear
  [sdvx@asphyxia] Unlocking songs
  [sdvx@asphyxia] Sending server information
  [sdvx@asphyxia] TypeError: Cannot read properties of undefined (reading 'arena_items')
  [sdvx@asphyxia] ====================================
  [sdvx@asphyxia] Calling common function
  [sdvx@asphyxia] Game: Exceed Gear
  [sdvx@asphyxia] Unlocking songs
  [sdvx@asphyxia] Sending server information
  [sdvx@asphyxia] TypeError: Cannot read properties of undefined (reading 'arena_items')
  [sdvx@asphyxia] ====================================
  [sdvx@asphyxia] Calling common function
  [sdvx@asphyxia] Game: Exceed Gear
  [sdvx@asphyxia] Unlocking songs
  [sdvx@asphyxia] Sending server information
  [sdvx@asphyxia] TypeError: Cannot read properties of undefined (reading 'arena_items')
  [sdvx@asphyxia] ====================================
  [sdvx@asphyxia] Calling common function
  [sdvx@asphyxia] Game: Exceed Gear
  [sdvx@asphyxia] Unlocking songs
  [sdvx@asphyxia] Sending server information
  [sdvx@asphyxia] TypeError: Cannot read properties of undefined (reading 'arena_items')
  [sdvx@asphyxia] ====================================
  [sdvx@asphyxia] Calling common function
  [sdvx@asphyxia] Game: Exceed Gear
  [sdvx@asphyxia] Unlocking songs
  [sdvx@asphyxia] Sending server information
  [sdvx@asphyxia] TypeError: Cannot read properties of undefined (reading 'arena_items')
  [sdvx@asphyxia] ====================================
  [sdvx@asphyxia] Calling common function
  [sdvx@asphyxia] Game: Exceed Gear
  [sdvx@asphyxia] Unlocking songs
  [sdvx@asphyxia] Sending server information
  [sdvx@asphyxia] TypeError: Cannot read properties of undefined (reading 'arena_items')
  [sdvx@asphyxia] ====================================
  [sdvx@asphyxia] Calling common function
  [sdvx@asphyxia] Game: Exceed Gear
  [sdvx@asphyxia] Unlocking songs
  [sdvx@asphyxia] Sending server information
  [sdvx@asphyxia] TypeError: Cannot read properties of undefined (reading 'arena_items')
  [sdvx@asphyxia] ====================================
  [sdvx@asphyxia] Calling common function
  [sdvx@asphyxia] Game: Exceed Gear
  [sdvx@asphyxia] Unlocking songs
  [sdvx@asphyxia] Sending server information
  [sdvx@asphyxia] TypeError: Cannot read properties of undefined (reading 'arena_items')
  [sdvx@asphyxia] ====================================
  [sdvx@asphyxia] Calling common function
  [sdvx@asphyxia] Game: Exceed Gear
  [sdvx@asphyxia] Unlocking songs
  [sdvx@asphyxia] Sending server information
  [sdvx@asphyxia] TypeError: Cannot read properties of undefined (reading 'arena_items')
  [sdvx@asphyxia] ====================================
  [sdvx@asphyxia] Calling common function
  [sdvx@asphyxia] Game: Exceed Gear
  [sdvx@asphyxia] Unlocking songs
  [sdvx@asphyxia] Sending server information
  [sdvx@asphyxia] TypeError: Cannot read properties of undefined (reading 'arena_items')
  [sdvx@asphyxia] ====================================
  [sdvx@asphyxia] Calling common function
  [sdvx@asphyxia] Game: Exceed Gear
  [sdvx@asphyxia] Unlocking songs
  [sdvx@asphyxia] Sending server information
  [sdvx@asphyxia] TypeError: Cannot read properties of undefined (reading 'arena_items')
  [sdvx@asphyxia] ====================================
  [sdvx@asphyxia] Calling common function
  [sdvx@asphyxia] Game: Exceed Gear
  [sdvx@asphyxia] Unlocking songs
  [sdvx@asphyxia] Sending server information
  [sdvx@asphyxia] TypeError: Cannot read properties of undefined (reading 'arena_items')
  [sdvx@asphyxia] ====================================
  [sdvx@asphyxia] Calling common function
  [sdvx@asphyxia] Game: Exceed Gear
  [sdvx@asphyxia] Unlocking songs
  [sdvx@asphyxia] Sending server information
  [sdvx@asphyxia] TypeError: Cannot read properties of undefined (reading 'arena_items')
  [sdvx@asphyxia] ====================================
  [sdvx@asphyxia] Calling common function
  [sdvx@asphyxia] Game: Exceed Gear
  [sdvx@asphyxia] Unlocking songs
  [sdvx@asphyxia] Sending server information
  [sdvx@asphyxia] TypeError: Cannot read properties of undefined (reading 'arena_items')

**Comment by 22vv0** [comment]
yup, to run dev mode properly, you will need to add these 3 files from the core zip file to your plugins folder:
![image](https://github.com/user-attachments/assets/71d9e24a-c11d-4dee-be0e-3d9b80e6db0f)
and change target to "es2020" in the tsconfig.json. will make sure to add it in the guide next time.

as for the arena_items issue above, what do you have set on the Arena season setting in asphyxia? it seems to be having a problem with your current selection.

**Comment by nian03240324** [comment]
I noticed if I turn on "Unlock All Valkyrie and Premium Items",I got error "ただいま回線が混雑しています。再度お試しください。"
